name: pokedex
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  go_router: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/types/
